### PR TITLE
Function to batch together examples

### PR DESCRIPTION
**Pull request by EvgenyDyshlyuk**

### CODE REVIEW

**Comment by EvgenyDyshlyuk** [comment]
Please check the function

**Comment by life-efficient** [comment]
My fault for not leaving a clear spec in the issue, but this function is designed to create batches of examples from the entire dataset, for minibatch gradient descent. We wrote something similar in the multiclass classification notebook that you should check out.

Input: iterable dataset (size = num_examples_in_dataset x num_features_per_example)
Output: iterable of batches of examples (size = (num_batches_that_result x num_examples_per_batch x num_features_per_example)

**Comment by EvgenyDyshlyuk** [comment]
Function batch_data updated

**Review by life-efficient — APPROVED** [review]
Nice
fixes #1

**Pull request merged**
